### PR TITLE
Add dotenv

### PR DESCRIPTION
**Pull request by arvinxx**
- add dotenv configuration
 - add more notarization log info

relative issue: #15

### CODE REVIEW

**Comment by arvinxx** [comment]
hello,is there any update to merge it?

**Comment by Bug-Reaper** [comment]
I can't merge you, but as a humble copy-pasta man 💁‍♂️ I applaud your efforts

**Comment by andirsun** [comment]
@karaggeorge dude, can you please merge this ?

**Comment by andirsun** [comment]
@arvinxx  I am facing an error with this new PR
```
📦 Start notarizing com.webalys.streamline found at /Users/julianacaromoreno/actions-runner/_work/streamline-web/streamline-web/dist/mac-universal/Streamline.app
  ⨯ The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Error  failedTask=build stackTrace=TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Error
    at Object.writeFileSync (node:fs:2163:5)
    at module.exports (/Users/julianacaromoreno/actions-runner/_work/streamline-web/streamline-web/node_modules/electron-builder-notarize/index.js:99:6)
```
Its because this line of code 
```
fs.writeFileSync('notarization-error.log', error);
```

**Pull request merged**
