### PR TITLE
Use builder-effective-config.yml when available

### LINKED ISSUE #6: If you run electron-builder from the vue-cli notarizing fails
electron-builder-notarize looks for the appId in package.json/build/appId.

If you are running electron-builder via [vue-cli-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder), the configuration for the builder is instead stored in `vue.config.js`.

electron-builder-notarize should get the appId from electron-builder directly.

A workaround for now is to add the appId to `build` in package.json

### PR DESCRIPTION
**Pull request by karaggeorge**
Fix #6

### CODE REVIEW

**Comment by karaggeorge** [comment]
@ruudboon If you can check this and see if this would work for you, that'd be awesome

**Comment by ruudboon** [comment]
@karaggeorge this fixes the issue for me and lgtm.

**Review by ruudboon — APPROVED** [review]

**Comment by karaggeorge** [comment]
Released as `v1.1.3`

**Comment by ruudboon** [comment]
Awesome. Thnx @karaggeorge 
Would it be an idea to release on your github repo as well so we can easily spot the latest version?

**Pull request merged**
